CREATE DATABASE `inventory` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
CREATE TABLE `stocks` (
  `SNO` int(11) NOT NULL AUTO_INCREMENT,
  `PRODUCTNAME` varchar(45) DEFAULT NULL,
  `PRODUCTDESCRIPTION` varchar(45) DEFAULT NULL,
  `qty` int(5) DEFAULT NULL,
  `RATE` float DEFAULT NULL,
  PRIMARY KEY (`SNO`)
) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
